#!/usr/bin/env python3.13

import json
import shutil
from pathlib import Path

# When running a Python script, parent directory is added to sys.path
from includes.utils.subprocess import run_cmd

ROOT_DIR = Path(__file__).resolve().parent.parent


def build() -> None:
    print(f"ROOT_DIR    = {ROOT_DIR}")
    print()

    # Remove target directory (if it exists) for a clean build
    target_dir = ROOT_DIR / "target"
    if target_dir.exists():
        if target_dir.is_file():
            target_dir.unlink()
        else:
            shutil.rmtree(target_dir)

    exit_code, _, _ = run_cmd(f"bun tsc --outDir {str(target_dir / 'dist')!r}")
    if exit_code != 0:
        exit(exit_code)

    with open(ROOT_DIR / "package.json", "r") as f:
        package_json = json.load(f)

    build_package_json = {
        k: package_json[k]
        for k in [
            "name",
            "version",
            "description",
            "author",
            "main",
            "exports",
            "dependencies",
        ]
    }
    # Optional fields
    for opt_k in [
        "license",
        "types",
        "packageManager",
        "repository",
        "publishConfig",
        "keywords",
    ]:
        if opt_k in package_json:
            build_package_json[opt_k] = package_json[opt_k]

    build_package_json_str = json.dumps(build_package_json, indent=2)
    build_package_json_str.replace("src/", "dist/")

    with open(target_dir / "package.json", "w") as f:
        f.write(build_package_json_str)

    print("Build completed successfully.")


build()
